### ISSUE TITLE
Redirect URL

### ISSUE THREAD

**Issue by Pool0513** [FloFlal/node-red-ewelink-v2-oauth#1]
Hello FloFlal,

First of all thank you for bringing this project.

I can't figure out what to do with the redirect url field.
If I do understand right, I should have a server listening to some port to redirect the token there. 
But I cannot figure out how to bring this server to life !

Maybe I'm completely wrong there...

Could you please help and advise ?

Thank you

**Comment by Pool0513** [comment]
forget my message I have found how to do it.

I used http://localnoderedaddress:localport/ewelink-auth/auth/callback

It worked :)

**Comment by FloFlal** [comment]
Hello !

Thank you for your interest for my nodes.

In the 1st release of it, I forgot to put the basic documentation I prepared.

It is now the case and as you already figgured out, the library is providing the listening redirect URL.

Good if it worked for you.
